<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521083938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER orden DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_zapatilla_imagen_zapatilla_id RENAME TO IDX_83FFA2E696F9B908');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER id SET DEFAULT nextval(\'zapatilla_imagen_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE zapatilla_imagen ALTER orden SET DEFAULT 0');
        $this->addSql('ALTER INDEX idx_83ffa2e696f9b908 RENAME TO idx_zapatilla_imagen_zapatilla_id');
    }
}
