<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421223940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE carrito (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_creacion DATE NOT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77E6BED5DB38439E ON carrito (usuario_id)');
        $this->addSql('CREATE TABLE categoria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE detalle_pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad INT NOT NULL, precio_momento NUMERIC(10, 2) NOT NULL, pedido_id INT DEFAULT NULL, zapatilla_id INT DEFAULT NULL, carrito_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A834F5694854653A ON detalle_pedido (pedido_id)');
        $this->addSql('CREATE INDEX IDX_A834F56996F9B908 ON detalle_pedido (zapatilla_id)');
        $this->addSql('CREATE INDEX IDX_A834F569DE2CF6E7 ON detalle_pedido (carrito_id)');
        $this->addSql('CREATE TABLE pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha DATE NOT NULL, total NUMERIC(10, 2) NOT NULL, metodo_de_pago VARCHAR(255) NOT NULL, direccion_de_envio VARCHAR(255) NOT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4EC16CEDB38439E ON pedido (usuario_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE vendedor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dni VARCHAR(20) NOT NULL, documentacion VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, fecha_solicitud DATE NOT NULL, fecha_aprobacion DATE DEFAULT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9797982EDB38439E ON vendedor (usuario_id)');
        $this->addSql('CREATE TABLE zapatilla (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, modelo VARCHAR(255) NOT NULL, marca VARCHAR(255) NOT NULL, talla NUMERIC(10, 1) NOT NULL, precio NUMERIC(10, 2) NOT NULL, stock INT NOT NULL, categoria_id INT NOT NULL, vendedor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_484948B33397707A ON zapatilla (categoria_id)');
        $this->addSql('CREATE INDEX IDX_484948B38361A8B8 ON zapatilla (vendedor_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE carrito ADD CONSTRAINT FK_77E6BED5DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F5694854653A FOREIGN KEY (pedido_id) REFERENCES pedido (id)');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F56996F9B908 FOREIGN KEY (zapatilla_id) REFERENCES zapatilla (id)');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F569DE2CF6E7 FOREIGN KEY (carrito_id) REFERENCES carrito (id)');
        $this->addSql('ALTER TABLE pedido ADD CONSTRAINT FK_C4EC16CEDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE vendedor ADD CONSTRAINT FK_9797982EDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE zapatilla ADD CONSTRAINT FK_484948B33397707A FOREIGN KEY (categoria_id) REFERENCES categoria (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zapatilla ADD CONSTRAINT FK_484948B38361A8B8 FOREIGN KEY (vendedor_id) REFERENCES usuario (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carrito DROP CONSTRAINT FK_77E6BED5DB38439E');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F5694854653A');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F56996F9B908');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F569DE2CF6E7');
        $this->addSql('ALTER TABLE pedido DROP CONSTRAINT FK_C4EC16CEDB38439E');
        $this->addSql('ALTER TABLE vendedor DROP CONSTRAINT FK_9797982EDB38439E');
        $this->addSql('ALTER TABLE zapatilla DROP CONSTRAINT FK_484948B33397707A');
        $this->addSql('ALTER TABLE zapatilla DROP CONSTRAINT FK_484948B38361A8B8');
        $this->addSql('DROP TABLE carrito');
        $this->addSql('DROP TABLE categoria');
        $this->addSql('DROP TABLE detalle_pedido');
        $this->addSql('DROP TABLE pedido');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE vendedor');
        $this->addSql('DROP TABLE zapatilla');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
